import json, os

def esc(s):
    if not s: return ''
    s = str(s).replace('<','&lt;').replace('>','&gt;').replace('{','&#123;').replace('}','&#125;')
    lines = []
    for line in s.split('\n'):
        if line.lstrip().startswith('|') or '---|' in line or '|---' in line:
            lines.append(line)
        else:
            lines.append(line.replace('|','&#124;'))
    return '\n'.join(lines)

md = ['# 休食看板 V9 · 数据底池 + Claude 聚类全过程', '']
md.append('> 这份文档是 V9 改造的白盒——把数据从哪来、Claude 怎么聚的、每个方法挑了哪些笔记，全部列清楚。')
md.append('')
md.append('## 1. 数据来源')
md.append('')
md.append('**基础表**：`redcdm.dm_ecm_note_fullchain_guide_1d_di`（dataset 1922 同源）')
md.append('**关联表**（6 表 JOIN）：')
md.append('')
md.append('| 表 | 用途 | JOIN key |')
md.append('|---|---|---|')
md.append('| `redcdm.dwd_con_note_info_all_df` | 笔记 title/content/video_asr_text | note_id |')
md.append('| `redcdm.dim_ecm_algo_note_label_df` | 算法质量分 / 购买意图分 | note_id |')
md.append('| `redcdm.dim_ecm_note_extend_df` | 电商笔记品类 / 多商品标记 | note_id |')
md.append('| `redcdm.dim_goods_base_df` | 商品维度（名/价/品牌/类目） | goods_id |')
md.append('| `redapp.app_ecm_ark_ai_note_score_base_nd_di` | **封面 URL（已 CDN 化）** | note_id |')
md.append('| `reddw.dw_soc_discovery_comment_detail_day` | 评论 Top5（高赞）| discovery_id |')
md.append('')
md.append('**时间窗**：2026-04-13 → 2026-06-11（60 天）')
md.append('')
md.append('**过滤**：')
md.append("- `seller_industry = '休食'`（行业品类，非部门）")
md.append("- `bridge_type IN ('goods_v2','goods_seller')` （仅商品笔记）")
md.append('- `SUM(note_imp_num) >= 500 AND SUM(dgmv) >= 100`')
md.append('')
md.append('**三层切分**：')
md.append('- 爆款：DGMV >= 50000 元（200 条）')
md.append('- 优秀：DGMV 10000-50000 元（200 条）')
md.append('- 黑马：曝光 < 10000 但 GPM > 100（200 条）')
md.append('- **共 600 条**')
md.append('')
md.append('**SQL 执行**：')
md.append('- msgId: `59770b4d-e3f8-447e-af5f-05e76ca59a12`')
md.append('- 跑时：30 分钟（11:25 提交 → 11:58 完成）')
md.append('- 产出：600 条 × 43 字段 / 1.8MB CSV')
md.append('')

md.append('## 2. 8 池切分（4 指标 × 2 形态）')
md.append('')
md.append('从 600 条按指标排序取 Top 80 → 过滤异常 → 每池 60 条进 Claude')
md.append('')
md.append('**指标定义**（GPM 漏斗）：')
md.append('- CTR1 = clk/imp（封面到点击）')
md.append('- CTR2 = gv/clk（笔记到商品卡）')
md.append('- CVR = buy/gv（商品卡到下单）')
md.append('- 件单价 = dgmv/buy')
md.append('')
md.append('**异常过滤规则**：')
md.append('- CTR2 失真：gv > clk × 1.5（商品卡有外部入口）')
md.append('- CVR > 100%（数据异常）')
md.append('- 件单价 > 5000 元（极端长尾）')
md.append('- imp < 100 / clk < 5 / gv < 1 / buy < 1')
md.append('- 过滤后：544/600 条进入 8 池')
md.append('')
md.append('**8 池统计**：')
md.append('')
md.append('| 池 | 60 条指标中位 | 60 条 Max | 形态 |')
md.append('|---|---|---|---|')
md.append('| ctr1_pic | 15.4% | 36.4% | 图文 |')
md.append('| ctr1_vid | 9.9% | 21.3% | 视频 |')
md.append('| ctr2_pic | 0.60% | 1.39% | 图文 |')
md.append('| ctr2_vid | 0.84% | 1.48% | 视频 |')
md.append('| cvr_pic | 16.3% | 64.5% | 图文 |')
md.append('| cvr_vid | 16.5% | 100.0% | 视频 |')
md.append('| price_pic | 2541 元 | 4035 元 | 图文 |')
md.append('| price_vid | 978 元 | 4350 元 | 视频 |')
md.append('')
md.append('**ASR 覆盖率**：视频笔记 278 条，含 ASR 258 条 = **92.8%**（远超 DEEP_REPORT 估算的 33%）')
md.append('**字段完整度**：cover_url 100% / goods_name 100% / top5_cmts 80.7% / quality 99.8%')
md.append('')

md.append('## 3. 喂给 Claude 的 Prompt 模板')
md.append('')
md.append('8 池每个独立喂 Claude（isolated session 一次性调用），prompt 结构：')
md.append('')
md.append('```text')
md.append('# 任务：归纳「休食 · <形态> · <指标>」的内容方法')
md.append('')
md.append('## 你的任务')
md.append('1. 把这 60 条笔记按「内容方法」聚类（不是按品类/品牌）')
md.append('2. 归纳出 4-5 个独立方法（必须有显著差异）')
md.append('3. 每方法包含：method_name / essence / why_works / signals')
md.append('   / applicable_category / note_ids（>=5 条）')
md.append('4. 最后给出 cluster_rationale')
md.append('')
md.append('## 红线')
md.append('- 不许编标题/亮点：方法依据必须能从笔记里找到证据')
md.append('- 不许预设方法（不要套现成标签）')
md.append('- 必须从数据归纳：先看完 60 条找规律，再定方法名')
md.append('- 至少 1 个方法包含反直觉发现')
md.append('- 视频池关注 ASR；图文池关注正文段落结构')
md.append('')
md.append('## 候选笔记池（60 条）')
md.append('### [1] note_id=... | gpm=... | 指标=... | imp=...')
md.append('- 商家/商品/价格/品类')
md.append('- 标题/正文(前200)/ASR(前300)/Top评论(前200)')
md.append('```')
md.append('')
md.append('**每池 prompt 大小**：27-43k 字符（60 条笔记完整字段）')
md.append('')

md.append('## 4. 聚类结果（5/8 已完成）')
md.append('')

name_map = {
    'ctr1_pic':'4.1 CTR1 · 图文', 'ctr1_vid':'4.2 CTR1 · 视频',
    'ctr2_pic':'4.3 CTR2 · 图文', 'ctr2_vid':'4.4 CTR2 · 视频',
    'cvr_pic':'4.5 CVR · 图文',
}

for pool in ['ctr1_pic', 'ctr1_vid', 'ctr2_pic', 'ctr2_vid', 'cvr_pic']:
    p = f'data/v9_clusters/{pool}.cluster.json'
    if not os.path.exists(p): continue
    d = json.load(open(p))
    md.append(f"### {name_map[pool]}")
    md.append('')
    md.append(f"- 输入 60 条候选笔记 → Claude 聚类")
    md.append(f"- subagent: `{d.get('subagent_session') or d.get('subagent')}`")
    md.append(f"- 耗时：{d.get('runtime_sec')}秒")
    md.append('')
    
    if 'methods' in d:
        md.append('| 方法 | 笔记数 | 适配品类 | 核心定义 |')
        md.append('|---|---|---|---|')
        for m in d['methods']:
            cat = ' / '.join(m['applicable_category'][:3])
            md.append(f"| {esc(m['method_name'])} | {len(m['note_ids'])} | {esc(cat)} | {esc(m['essence'])} |")
        md.append('')
        md.append(f"**聚类逻辑**：{esc(d.get('cluster_rationale',''))}")
        md.append('')
        md.append('**每方法第 1 个代表案例（点开看小红书原笔记）**：')
        md.append('')
        md.append('| 方法 | note_id | 链接 |')
        md.append('|---|---|---|')
        for m in d['methods']:
            if m['note_ids']:
                nid = m['note_ids'][0]
                md.append(f"| {esc(m['method_name'])} | `{nid}` | https://www.xiaohongshu.com/explore/{nid} |")
        md.append('')
        md.append('**每方法完整 note_ids 清单**：')
        md.append('')
        for m in d['methods']:
            ids = ', '.join(f'`{nid}`' for nid in m['note_ids'])
            md.append(f"- **{esc(m['method_name'])}** ({len(m['note_ids'])} 条): {ids}")
        md.append('')
    else:
        md.append('| 方法 | 笔记数 | 适配品类 |')
        md.append('|---|---|---|')
        for name, cnt, cats in d['methods_brief']:
            md.append(f"| {esc(name)} | {cnt} | {esc(' / '.join(cats[:4]))} |")
        md.append('')
        md.append(f"**聚类逻辑**：{esc(d.get('rationale',''))}")
        md.append('')

md.append('## 5. 笔记原始数据池（可下钻）')
md.append('')
md.append('每池 60 条原始数据 JSON 存储位置：')
md.append('')
md.append('```')
md.append('/home/node/.openclaw/workspace/xushi-trends-cron/work/data/v9_pools/')
md.append('├── ctr1_pic.json  (60 条)')
md.append('├── ctr1_vid.json')
md.append('├── ctr2_pic.json')
md.append('├── ctr2_vid.json')
md.append('├── cvr_pic.json')
md.append('├── cvr_vid.json   ← 跑中')
md.append('├── price_pic.json ← 跑中')
md.append('└── price_vid.json ← 跑中')
md.append('```')
md.append('')
md.append('每条笔记字段示例：')
md.append('')
md.append('```json')
md.append('&#123;')
md.append('  "note_id": "6a213d4600000000350283c3",')
md.append('  "seller": "咖皇旗舰店",')
md.append('  "title": "泪水不用打湿剪脂餐了",')
md.append('  "content": "正文前 300 字...",')
md.append('  "asr": "视频 ASR 前 400 字...",')
md.append('  "goods_name": "咖皇剪脂代餐",')
md.append('  "goods_price": "128.00",')
md.append('  "brand": "咖皇",')
md.append('  "goods_cat3": "代餐麦片",')
md.append('  "cover_url": "https://ci.xiaohongshu.com/...",')
md.append('  "top_cmts": "Top5 高赞评论拼接...",')
md.append('  "tier": "爆款",')
md.append('  "ctr1_pct": 28.1, "ctr2_pct": 1.2, "cvr_pct": 7.2, "price_yuan": 168.0,')
md.append('  "gpm": 232, "imp": 52389,')
md.append('  "note_type": "图文"')
md.append('&#125;')
md.append('```')
md.append('')

md.append('## 6. 待办（3 池在跑）')
md.append('')
md.append('- ⏳ cvr_vid（CVR 视频）')
md.append('- ⏳ price_pic（件单价 图文）')
md.append('- ⏳ price_vid（件单价 视频）')
md.append('')
md.append('拿到 8 组结果后，下一步：')
md.append('1. 主会话手工 merge：跨池重复方法合并 / 过滤<5 笔记的小方法')
md.append('2. 每池选 1 个 **王炸**（综合 rank：笔记数 × GPM 中位）')
md.append('3. 8 个王炸用 Claude 生成完整 5 件套 SOP（封面/标题/脚本/商品卡/评论）')
md.append('4. 写 build_v9.py 重做 UI，每个指标 Tab 结构：')
md.append('   - 顶部：行业 P50/P75（不变）')
md.append('   - 🏆 王炸方法（5 件套，红色边框）')
md.append('   - ◇ 其他 N 个方法（精简卡 + 案例横向铺）')
md.append('   - 📋 全 X 篇完整案例榜（折叠，可筛品类）')
md.append('')
md.append('---')
md.append('')
md.append('生成时间：2026-06-12 12:30 / 当前进度：5/8 聚类已完成')

content = '\n'.join(md)
open('V9_DATA_LINEAGE.md','w', encoding='utf-8').write(content)
print(f"written: {len(content)} chars")
